# Generated by Django 5.2.12 on 2026-03-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_prescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-start_date', 'id'], 'verbose_name': 'Prescription', 'verbose_name_plural': 'Prescriptions'},
        ),
        migrations.AlterField(
            model_name='prescription',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('valide', 'valide'), ('en_attente', 'en attente'), ('suppr', 'supprimé')], db_index=True, default='en_attente', max_length=16),
        ),
    ]
